# Generated by Django 5.2 on 2025-04-17 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(default='', max_length=20)),
                ('area', models.CharField(choices=[('Catastro', 'Catastro'), ('Relaciones Internacionales', 'Relaciones Internacionales'), ('Economia', 'Economia'), ('Unidad de Aseguramiento', 'Unidad Aseguramiento'), ('Gestion del Planeamiento', 'Gestion Planeamiento'), ('Ordenamiento', 'Ordenamiento'), ('Urbanismo', 'Urbanismo'), ('Juridico', 'Juridico'), ('Cuadros', 'Cuadros'), ('Esquema y Planes', 'Esquema Y Planes'), ('Comunicacion Institucional', 'Comunicacion Institucional'), ('Ciencia y Técnica', 'Ciencia Y Tecnica'), ('Recursos Humanos', 'Recursos Humanos'), ('Seguridad y Protección', 'Seguridad Proteccion'), ('Servicios Generales', 'Servicios Generales'), ('Atención a la población', 'Atencion A La Poblacion')], max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_ini', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(default='', null=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='------')),
                ('realizada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_cliente', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
