# Generated by Django 5.2 on 2025-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_ticket_delete_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_ini',
            field=models.DateTimeField(default='2025-04-17 22:58:40'),
        ),
    ]
