# Generated by Django 5.2 on 2025-04-18 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_ticket_fecha_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
