# Generated by Django 5.2 on 2025-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_ticket_fecha_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
