# Generated by Django 5.2 on 2025-04-21 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_ticket_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'Técnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
